name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.13.5
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  oauth2: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  http_interceptor: ^2.0.0-beta.8
  test: ^1.24.6
  build_runner: ^2.4.6
  json_serializable: ">=6.7.1 <7.0.0"
